### PR TITLE
fixed vertical align of columns

### PR DESCRIPTION
**Pull request by radian628**

### CODE REVIEW

**Comment by VVill-ga** [comment]
Are pixels a suitable unit for media queries like this? I wonder if something more dynamic should be used like `em`?

**Comment by radian628** [comment]
good point--- we may want to ensure that pixel ratios stay consistent with one of those meta tags

**Comment by radian628** [comment]
looks like you already added that, nice:
`<meta name="viewport" content="width=device-width, initial-scale=1.0" />`

this should make the pixels device independent (so for instance high DPI phone screens won't render everything super small)

**Comment by radian628** [comment]
I can confirm it works with weird device pixel ratios (tested it in firefox with its phone simulator settings)

**Comment by VVill-ga** [comment]
LGTM thx

**Pull request merged**
